#!/command/with-contenv bash

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping migrations because we could not detect a Laravel install..."
  exit 0
fi

cd "$WEBUSER_HOME" || exit 0

if [ "${LANDLORD_MIGRATE:="true"}" == "true" ]; then
  echo "Processing landlord migrations..."

  {
    s6-setuidgid webuser php "$WEBUSER_HOME/artisan" migrate --database=landlord --path=database/landlord --force --isolated \
    && echo "Landlord migrations finished!"
  } || {
    echo "Landlord migrations failed!"

    # TODO: Do something to send an alert that migration failed. Currently this will NOT stop the container.
  }
else
    echo "Skipping landlord migrations because it was specifically disabled..."
fi

if [ "${TENANT_MIGRATE:="true"}" == "true" ]; then
  echo "Processing tenant migrations..."

  {
    s6-setuidgid webuser php "$WEBUSER_HOME/artisan" tenants:artisan "migrate --database=tenant --force --isolated" \
    && echo "Tenant migrations finished!"
  } || {
    echo "Tenant migrations failed!"

    # TODO: Do something to send an alert that migration failed. Currently this will NOT stop the container.
  }
else
    echo "Skipping tenant migrations because it was specifically disabled..."
fi

exit 0
