#!/command/with-contenv bash

# Exit on error
set -e

# Check to see if an Artisan file exists and assume it means Laravel is configured.
if [ -f "$WEBUSER_HOME"/artisan ] && [ "${LARAVEL_SCHEDULER_ENABLED:="true"}" == "true" ]; then
        cd "$WEBUSER_HOME"

        USERNAME=$(id -nu "$PUID")

        {
        echo "Clearing schedule cache..." \
        && s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" schedule:clear-cache \
        && echo "Schedule cache cleared!"
        } || {
        echo "Schedule cache clear failed!"
        }

        echo "Starting Cron..."

        touch /etc/crontab /etc/cron.*/*

        exec cron -f
else
    echo "👉 Skipping cron because we could not detect a Laravel install or it was specifically disabled..."

    tail -f /dev/null
fi
