name: Pull Requests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-checks:
    name: Code Checks

    uses: ./.github/workflows/ci.yml
    secrets:
      pat-token: ${{ secrets.PAT }}